name: Update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          repository: santacrab2/PKHeX-Plugins
          ref: cherrytree

      - name: Checkout PKHeX
        run: |
          git clone -q --depth=5 --branch=master https://github.com/kwsch/PKHeX.git ${{ github.workspace }}/PKHeX

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install NuGet
        run: |
          nuget update -self
          nuget install nuget.commandline -OutputDirectory .nuget -ExcludeVersion
          echo "$(pwd)/.nuget/nuget.commandline/tools" >> $GITHUB_PATH

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet dependencies for PKHeX-Plugins
        run: nuget restore ${{ github.workspace }}/PKHeX-Plugins.sln

      - name: Restore NuGet dependencies for PKHeX
        run: nuget restore ${{ github.workspace }}/PKHeX/PKHeX.sln -NoCache

      - name: Build PKHeX.Core
        run: |
          msbuild ${{ github.workspace }}/PKHeX/PKHeX.Core/PKHeX.Core.csproj /p:Configuration=Release /p:Platform="Any CPU"

      - name: Build PKHeX.Core.AutoMod
        run: |
          msbuild ${{ github.workspace }}/PKHeX.Core.AutoMod/PKHeX.Core.AutoMod.csproj /p:Configuration=Release /p:Platform="Any CPU"

      - name: Update deps directory
        run: |
          mkdir -p ${{ github.workspace }}/deps
          cp "${{ github.workspace }}/PKHeX.Core.AutoMod/bin/Any CPU/Release/net9.0/PKHeX.Core.AutoMod.dll" "${{ github.workspace }}/deps/PKHeX.Core.AutoMod.dll"
          cp "${{ github.workspace }}/PKHeX/PKHeX.Core/bin/Any CPU/Release/net9.0/PKHeX.Core.dll" "${{ github.workspace }}/deps/PKHeX.Core.dll"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add deps/PKHeX.Core.dll deps/PKHeX.Core.AutoMod.dll
          git commit -m "Update PKHeX.Core.dll and PKHeX.Core.AutoMod.dll"
          git push
