name: .NET Desktop Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          repository: santacrab2/PKHeX-Plugins
          ref: cherrytree

      - name: Checkout PKHeX
        run: |
          git clone -q --depth=5 --branch=master https://github.com/kwsch/PKHeX.git ${{ github.workspace }}/PKHeX

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install NuGet
        run: |
          nuget update -self
          nuget install nuget.commandline -OutputDirectory .nuget -ExcludeVersion
          echo "$(pwd)/.nuget/nuget.commandline/tools" >> $GITHUB_PATH

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet dependencies for PKHeX-Plugins
        run: nuget restore ${{ github.workspace }}/PKHeX-Plugins.sln

      - name: Restore NuGet dependencies for PKHeX
        run: nuget restore ${{ github.workspace }}/PKHeX/PKHeX.sln -NoCache

      - name: Build PKHeX.Core
        run: |
          msbuild ${{ github.workspace }}/PKHeX/PKHeX.Core/PKHeX.Core.csproj /p:Configuration=Release /p:Platform="Any CPU"

      - name: Copy PKHeX.Core.dll to NuGet cache
        shell: powershell
        run: |
          $nugetver = (Get-ChildItem "$env:UserProfile/.nuget/packages/pkhex.core" | Sort-Object -Property LastWriteTime -Descending)[0].Name
          Copy-Item "${{ github.workspace }}/PKHeX/PKHeX.Core/bin/Any CPU/Release/net9.0/PKHeX.Core.dll" "$env:UserProfile/.nuget/packages/pkhex.core/$nugetver/lib/net9.0"

      - name: Build PKHeX-Plugins
        run: |
          msbuild ${{ github.workspace }}/PKHeX-Plugins.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Prepare artifacts
        run: |
          mkdir bin
          xcopy ${{ github.workspace }}\AutoLegalityMod\bin\Release\net9.0-windows\AutoModPlugins.dll ${{ github.workspace }}\bin /Y

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PKHeX-Plugins
          path: ${{ github.workspace }}/bin
